stages:
  - Build
  - Setting
  - Deploy

Gatsby Build:
  stage: Build
  image: node:latest
  before_script:
    - cd /volume1/docker/Blog-Front
    - git pull origin master
  script:
    - yarn
    - yarn build

Gatsby Kill Nohup:
  stage: Setting
  script:
    - kill 9 `ps -ef | awk '$9 ~ /Blog-Front/ {print $2}'`

Gatsby Run Nohup:
  stage: Deploy
  script:
    - nohub yarn serve &
