stages:
  - Build
  - Setting
  # - Deploy

Gatsby Build:
  stage: Build
  image: node:latest
  before_script:
    - cd /volume1/docker/Blog-Front
    - git pull origin master
  script:
    - echo "npm install을 시작합니다."
    - yarn
    - echo "gatsby buld를 시작합니다."
    - yarn build
  only:
    - merge_requests

Gatsby Kill Nohup:
  stage: Setting
  script:
    - echo "기존 배포중인 블로그를 정지합니다."
    - kill 9 `ps -ef | awk '$9 ~ /Blog-Front/ {print $2}'`
    - echo "작업이 완료되었습니다."
    - echo "블로그를 실행해주세요."
  only:
    - merge_requests

# Gatsby Run Nohup:
#   stage: Deploy
#   before_script:
#     - cd /volume1/docker/Blog-Front
#   script:
#     - nohup yarn serve &
#     - echo "Blog Deployed"
#   only:
#     - merge_requests
